name = "srcc-admin-dashboard"
compatibility_date = "2024-04-05"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "srcc-erp-db"
database_id = "251ad6fa-5857-4cf5-9608-e66e45a85e19"

[vars]
PYTHON_API_URL = "https://kroni19-python-parser.hf.space"
ROOM_PYTHON_API_URL = "https://kroni19-python-parser.hf.space"
