import React from 'react';
import { logoBase64 } from '../assets/logo';
import { format } from 'date-fns';

interface AbsenceRecord {
  id: number;
  teacher_name: string;
  start_date: string;
  end_date: string;
  marked_by: string;
  created_at: string;
}

interface PrintLetterheadProps {
  records?: AbsenceRecord[];
  dateStr: string;
  title?: string;
  children?: React.ReactNode;
  pageBreakAfter?: 'always' | 'auto';
}

export function PrintLetterhead({ records, dateStr, title = "TEACHERS ON LEAVE", children, pageBreakAfter = 'always' }: PrintLetterheadProps) {
  const computeDays = (start: string, end: string): number => {
    const s = new Date(start);
    const e = new Date(end);
    const diff = Math.round((e.getTime() - s.getTime()) / (1000 * 60 * 60 * 24));
    return diff + 1; // inclusive
  };

  const ITEMS_PER_PAGE = 28;
  const chunkedPages: (AbsenceRecord | null)[][] = [];

  if (!records || records.length === 0) {
    chunkedPages.push(Array(ITEMS_PER_PAGE).fill(null));
  } else {
    for (let i = 0; i < records.length; i += ITEMS_PER_PAGE) {
      const chunk = records.slice(i, i + ITEMS_PER_PAGE) as (AbsenceRecord | null)[];
      while (chunk.length < ITEMS_PER_PAGE) {
        chunk.push(null);
      }
      chunkedPages.push(chunk);
    }
  }

  if (children) {
    return (
      <div className="print-page-container" style={{ pageBreakAfter }}>
          <div className="print-header">
            <div className="print-header-logo">
              <img src={logoBase64} alt="SRCC Logo" />
            </div>

            <div className="print-header-text">
              <div className="print-hindi-title">श्री राम कॉलेज ऑफ़ कॉमर्स</div>
              <div className="print-english-title">SHRI RAM COLLEGE OF COMMERCE</div>
              <div className="print-address-hindi">दिल्ली विश्वविद्यालय, मौरिस नगर, दिल्ली ११०००७</div>
              <div className="print-address-english">University of Delhi, Maurice Nagar, Delhi-110007</div>
              <div className="print-contact">
                <span><span className="print-hindi-inline">दूरभाष</span>: 27667905, 27666519</span>
                <span className="print-contact-sep">▪</span>
                <span><span className="print-hindi-inline">वेबसाइट</span> : www.srcc.edu</span>
                <span className="print-contact-sep">▪</span>
                <span><span className="print-hindi-inline">ईमेल</span> : principaloffice@srcc.du.ac.in</span>
              </div>
            </div>
            <div className="print-header-logo-right">
              <img src="/SRCC100.svg" alt="Centenary Logo" />
            </div>
          </div>

          <div className="print-title-row">
            <div className="print-report-title">{title}</div>
            <div className="print-report-date">Date: {dateStr}</div>
          </div>

          {children}

          <div className="print-footer pt-4" style={{ marginTop: 'auto' }}>
            <div className="print-footer-line"></div>
            <div className="print-footer-text text-center">
              Generated by SRCC Admin Assist • April 14, 2026
              <div style={{ marginTop: '2px' }}>Developed with Curiosity by <strong>Keshav Singal(24BC702)</strong></div>
            </div>
          </div>
      </div>
    );
  }

  return (
    <>
      {chunkedPages.map((pageRecords, pageIndex) => {
        // Calculate global starting index for S.No.
        const startNumber = pageIndex * ITEMS_PER_PAGE;
        
        return (
          <div 
            key={pageIndex} 
            className="print-page-container"
            style={{ 
              pageBreakAfter: pageIndex === chunkedPages.length - 1 ? pageBreakAfter : 'always',
            }}
          >
            {/* ===== LETTERHEAD HEADER ===== */}
            <div className="print-header">
              <div className="print-header-logo">
                <img src={logoBase64} alt="SRCC Logo" />
              </div>

              <div className="print-header-text">
                <div className="print-hindi-title">श्री राम कॉलेज ऑफ़ कॉमर्स</div>
                <div className="print-english-title">SHRI RAM COLLEGE OF COMMERCE</div>
                <div className="print-address-hindi">दिल्ली विश्वविद्यालय, मौरिस नगर, दिल्ली ११०००७</div>
                <div className="print-address-english">University of Delhi, Maurice Nagar, Delhi-110007</div>
                <div className="print-contact">
                  <span><span className="print-hindi-inline">दूरभाष</span>: 27667905, 27666519</span>
                  <span className="print-contact-sep">▪</span>
                  <span><span className="print-hindi-inline">वेबसाइट</span> : www.srcc.edu</span>
                  <span className="print-contact-sep">▪</span>
                  <span><span className="print-hindi-inline">ईमेल</span> : principaloffice@srcc.du.ac.in</span>
                </div>
              </div>

              <div className="print-header-logo-right">
                <img src="/SRCC100.svg" alt="Centenary Logo" />
              </div>
            </div>

            {/* ===== DATE + TITLE LINE ===== */}
            <div className="print-title-row">
              <div className="print-report-title">{title}</div>
              <div className="print-report-date">Date: {dateStr}</div>
            </div>

            {/* ===== DATA TABLE ===== */}
            <table className="print-table w-full">
              <thead>
                <tr>
                  <th style={{ width: '8%', textAlign: 'center' }}>S.No.</th>
                  <th style={{ width: '38%' }}>Faculty Name</th>
                  <th style={{ width: '22%' }}>From</th>
                  <th style={{ width: '22%' }}>To</th>
                  <th style={{ width: '10%', textAlign: 'center' }}>Days</th>
                </tr>
              </thead>
              <tbody>
                {pageRecords.map((record, rIndex) => {
                  const sNo = startNumber + rIndex + 1;
                  return (
                    <tr key={record?.id || `empty-${pageIndex}-${rIndex}`}>
                      <td style={{ textAlign: 'center' }}>{record ? sNo + '.' : ''}</td>
                      <td style={{ height: '26px' }}>{record ? record.teacher_name : ''}</td>
                      <td>{record ? format(new Date(record.start_date), 'dd MMM yyyy') : ''}</td>
                      <td>{record ? format(new Date(record.end_date), 'dd MMM yyyy') : ''}</td>
                      <td style={{ textAlign: 'center' }}>
                        {record ? computeDays(record.start_date, record.end_date) : ''}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>

            {/* ===== FOOTER ===== */}
            <div className="print-footer pt-4" style={{ marginTop: 'auto' }}>
              <div className="print-footer-line"></div>
              <div className="print-footer-text text-center">
                Generated by SRCC Admin Assist • April 14, 2026
                <div style={{ marginTop: '2px' }}>Developed with Curiosity by <strong>Keshav Singal(24BC702)</strong></div>
              </div>
            </div>
          </div>
        );
      })}
    </>
  );
}
